### ISSUE TITLE
Incomplete sequencing plate / incomplete index values

### ISSUE THREAD

**Issue by jwierz** [sandberg-lab/Spreading-Correction#3]
Hello!
We would like to use your tool to check some of our data as we (probably) had some cross-contamination. Our data is from 16S amplicon analysis to figure out the microbial community. Within the data, some samples have a very high count of certain ASV, some have very few and some (should) have none. We believe that the unspread.py script might help us solve this issue. 

As far as we understand we can specify the number of samples by giving the number of rows and columns. However, when the samples were sequenced, not the whole sequencing plate was used. Thus, some combinations of the two indices are empty and we get the error message: "number of cells in count file not same as specified". Now we don’t know how to fix that, as filling up with 0’s could mess up the regression. Do you have any suggestion how to handle this situation? That would be very appreciated. 
Thank you very much in advance!

**Comment by AntonJMLarsson** [comment]
Hi! 
The equation does assume that that all combinations of all the indexes are used. However, adding dummy counts of 0 where there is missing data is will work. The correction itself only removes counts and will never add them. The estimation of the rate will still work if it finds any ASV that it can use. 

If unspread.py doesn't find anything but you still think you have it (which is possible), you can quite easily figure out roughly what the spreading rate is by manually inspecting the count tables and find the samples with a high count and then dividing the samples with low counts with the samples of high counts. If you do that, it's possible to edit the script to hard-code the spreading rate by setting the spreading_rate variable explicitly.

Hope this helps.

Best Regards,

Anton

**Comment by jwierz** [comment]
Hi Anton!
Thank you for your quick reply! Adding dummy counts of 0 helped indeed to run the script. 

However, this resulted in a new problem: all samples with a non-high read count in a specific ASV had their reads counts corrected to 0 in this ASV. We don't believe this is correct, as we expect some true positive reads among the non-high samples. Is this also fixable by setting the spreading_rate and is this scientifically sound?

Again, thank you for your help!
cheers

**Comment by rturba** [comment]
Did you figure it out, @jwierz ? I'm curious to use this program with my metabarcode dataset as well.
