### ISSUE TITLE
IndexInfo file

### ISSUE THREAD

**Issue by ScaonE** [sandberg-lab/Spreading-Correction#5]
Dear all,

During the process of a typical Illumina sequencing run, where do you retrieve the equivalent of the "_mHSC_plate1HiSeq_counts_IndexInfo_anon.csv_" you are using as input?

Is it a raw file you retrieve at a given step?
Is the file created from the concatenation / parsing of many files? 

I did read the Nature Methods article and the Git repo but I am still unsure about this.
My wet lab team is asking for more details to retrieve such a file, thus the questions above.

Best regards

**Comment by AntonJMLarsson** [comment]
Hello,

This is the read count table usually obtained at the end of a typical software processing pipeline. I.e. the number of mapped reads per gene and cell.

Hope this helps.

Best,
Anton

**Comment by ScaonE** [comment]
Thanks for your answer

The "N.index.name" & "S.index.name" are not found routinely in the pipeline outputs I am given, this is why I was asking.
I'll dig a bit deeper on my side.

**Comment by AntonJMLarsson** [comment]
Those columns are added manually to inform the index layout. This is very important for the algorithm to work.

Best,
Anton
