### ISSUE TITLE
[--i5 STRING] [--i7 STRING] 

### ISSUE THREAD

**Issue by Samaneh14** [sandberg-lab/Spreading-Correction#6]
Hi,

Would you please more explain how to define the [--i5 STRING] [--i7 STRING], I am using read counts from a 384 well plate with cell bar-code names as the column names. 

Thanks in advance!

**Comment by AntonJMLarsson** [comment]
Hello,

Given that each row corresponds to a sample, the --i5 and --i7 parameters specify the cell barcode for the i5 and i7 adapters respectively. Please look in the README for an example. If your data is in the other configuration (i.e. each column is a sample), you can specify this with the --column option.

Let me know if you have any questions.

Anton

**Comment by Samaneh14** [comment]
Hi Anton,

Thanks for your answer. Yes, indeed the matrix consists cell barcodes as columns and genes as rows. I set the run command by  ./unspread.py matrix.csv --column 1

However, it still gives the following:

Reading file: matrix.csv
Traceback (most recent call last):
  File "~./unspread.py", line 69, in <module>
    df = df.sort_values(by=[i5_index_name,i7_index_name], ascending=[False, True])
  File "~/miniconda/envs/python3/lib/python3.9/site-packages/pandas/core/frame.py", line 5442, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "~/miniconda/envs/python3/lib/python3.9/site-packages/pandas/core/frame.py", line 5442, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "~/miniconda/envs/python3/lib/python3.9/site-packages/pandas/core/generic.py", line 1684, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'i5.index.name'

Should I adjust   i5 and i7 in addition to --column 1?

Best regards
Samaneh

**Comment by AntonJMLarsson** [comment]
Hello,
Yes, you need to change them to the actual name of the rows which have the i5 and i7 indexes.

Best,
Anton

**Comment by Samaneh14** [comment]
Dear Anton,

How may the code be adapted for the libraries with just cell barcodes and UMIs, when the i5 and i7 adapters are lacked?

Thanks in advance for your time.

Regards,
Samaneh

**Comment by AntonJMLarsson** [comment]
If your sequencing data is not dual indexed I don't recommend my software. If your experiment is single indexed with UMIs (like eg 10x) consider this software instead https://csglab.github.io/PhantomPurgeR/

**Comment by Samaneh14** [comment]
> If your sequencing data is not dual indexed I don't recommend my software. If your experiment is single indexed with UMIs (like eg 10x) consider this software instead https://csglab.github.io/PhantomPurgeR/

Dear Anton,

Thank you so much for the comment. Great solution.

Best regards
Samaneh
